name: Deploy to VM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /Users/sovannarith/Documents/Desktop__/15_SOEUN_SOVANNARITH_PVH_Web_Homework005
          git pull origin main
          docker compose down
          docker compose up -d --build --force-recreate
          docker image prune -f